{% set name = "twython" %}
{% set version = "3.6.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "488908e38aeb843f2565e1e5c54378a6104beab3b1e12718bd69c0e44fa3c1c9" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - requests >=2.1.0
    - requests-oauthlib >=0.4.0

test:
  imports:
    - twython
    - twython.streaming

about:
  home: https://github.com/ryanmcgrath/twython/
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: 'Actively maintained, pure Python wrapper for the     Twitter API. Supports both normal and streaming Twitter APIs'
  dev_url: https://github.com/ryanmcgrath/twython/
  doc_url: https://twython.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
