# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "TWvLCXaVGXTb5IRulTl8MOu/1OnoY0FbBh+sFBug1aRNlssjxskJwiPqlqUYAj/dK6suNlOsfy/zY7dVo8uRwBNxD1XWAS8NJPJ++1Dj8uYIUvOaN61Geu6/NKQNadNwHRs6vDrGclALBWLjv4Q1WuYXn6j5FJAQ86rYw34bNMqQGugDk4tuApSY9Vd+x/2q9UseFroPU96ySAv09Cbphixf5Ps4Ult0M1GwBvFHja6msrO5UomKOCDAQVvQ0/Pks/cGwuo0QCuWH3ONwcxK1iWH76+Z6eXJFfRQbR/jRAVG7fb3C68dMsm0VA94kix47TwTlh2WWiwEhJ0eH+u94szlZ/qCINGT7Gi1HGR7yq8OaCIZ4hClp8rQczYP4M+evW6HMNUUqKzRu+NUyb9RAAES2hROHHLH280H94F6+ImuulLBmz5B3WSP0og/Xg/W7qmOW5Yf/MHvvPPix8+Cbwu+0/FONjvoOc9QA3KdQ9qOoBoBsJPTFihnsbwBqMpHjA4SZQIv6FEUKz/zej8VHhUcFtyml1sDMcnhiV3mbGkM60BqKBGb8OVeAfxAw+DTnzkwdwKgdDhh+g3i8jMvc4SlYncjE9Ez+te+zL3PpvB3nN2Mea7B1sHtoQJ4y4WqFo+H75UWHOx7rHOxwZcmKKTc7SJHbqQ23pnIetBrldA="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
