travis:
  secure:
    BINSTAR_TOKEN: Abxdl472NialK7BL+XN8FvaESbLM7yR1NPyB2AUxsm60Yi8NH1WQIzWTkxJOp8hpMgR0T/M/gK0Qs2JB1cD320UYXYUOZ4/1aphdqmxhlijIOhuF0M/EH4CLxgH+FB4JjL8OLodAjdVN9uoLZhkvdlgiGwGCgeiDVki3wYnnhyeapXlniRxlarca+hoq1LEN6xos6l/yc9FUqjUA6WvwsVTmIdJ52UyFv0wCzb0x4lnwpRStkFRVEBnKJWK13juQzzuKyPYs67PeFkUv0Y8pdUJS3NfWmOp12bUXhMjXGYhFrBn64V1XLjTcminbBvluCMz3kOE0jqf6csiK9mLUO9EkrdjMBV0G49Ko+sTETMDTNEJCaf2oyF7vvrpY0GsecFJzXkLZNkYRZsmWAsIxUtHi0ZnqjnjtKAOJX19Vmr11ZezvHzrkOxUIkxm3V0hCh2G+6jHlgAUvb19FImOCzFEB21rIVpOlHm9O6zSRgiSd7XjC3YXgZrcl1rl97Uqh/0AW2sOTg1QuKbBF0l3GcHN5n8CMzyWgXL7uFDCpw9j2zx5e2iH214q0ObCV5Oo0Y/khQc2n6to2xiTXR+TWCFcQdN3ET+o0Qe3jMr5forbo54KOhGpYoo52frx8hjCQjE3YtRdpnZNazZR29prt+ma85ZpIfxSXe6g5KRm1Uo8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
