travis:
  secure:
    BINSTAR_TOKEN: KmqevSvS89368YaIfI8t4Bnpu4Fyo0LLOYTIrt0FaqM5IQ21YMChK243lD2SiSCKfyKXfBa8M+PA3jscMiDWAKBdovijMlPFvJMq4sCShuJN7ItSWNnKTk/HTr/mGmORfnGHibZB0rI8ijCysur+bsBCwSbceAcVI6Ps67f7dx8bLCuY9HHx8mU/5n0fxLkO5GdvdsATlOLw0RQMW0THAjMu4Y6feGy2eXlFHvjXvG2ahc+F0CEgAgj/I7d55XXNOcPqru+Ybsq+QK6oNDJVzgv3HPuP2tXrSKOdVn9ZtC5pQCVQo7GWncpvlacDRLMFMEufWqnS7iEfIu1i42yyDWji/sNMITWoF6KyAeyYcPCbhH+Nyw+wwtBY2xsmss1A2xbII8AqocAhsvIOu/Bk6p2TpU1DgkuTLyvQS7fgcW3v/aJO2So9X3K/vb7/Md4joQmWMbBRV41k9WKJVIpga9VxNhKr+ZAj0dnAgN95iC3cGJn8mLQGV0n6kmKNnv3o6FtQqWzIWVk/3hzHJPL9iIzKgG7K17zPTT2qk3ngjnZ7ufr1sUn4DzrkzdiUDcCuo7fXYISGAIYeLNJguh0CPeiQNJbnd/MbkO5vwL4VC1dOy77gd1ZYA6U7Yw1kSNaepcV70vWmARHuy5AnfEsUqAjAQxqj3q6s1pr127Xm5oU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
