travis:
  secure:
    BINSTAR_TOKEN: TWvLCXaVGXTb5IRulTl8MOu/1OnoY0FbBh+sFBug1aRNlssjxskJwiPqlqUYAj/dK6suNlOsfy/zY7dVo8uRwBNxD1XWAS8NJPJ++1Dj8uYIUvOaN61Geu6/NKQNadNwHRs6vDrGclALBWLjv4Q1WuYXn6j5FJAQ86rYw34bNMqQGugDk4tuApSY9Vd+x/2q9UseFroPU96ySAv09Cbphixf5Ps4Ult0M1GwBvFHja6msrO5UomKOCDAQVvQ0/Pks/cGwuo0QCuWH3ONwcxK1iWH76+Z6eXJFfRQbR/jRAVG7fb3C68dMsm0VA94kix47TwTlh2WWiwEhJ0eH+u94szlZ/qCINGT7Gi1HGR7yq8OaCIZ4hClp8rQczYP4M+evW6HMNUUqKzRu+NUyb9RAAES2hROHHLH280H94F6+ImuulLBmz5B3WSP0og/Xg/W7qmOW5Yf/MHvvPPix8+Cbwu+0/FONjvoOc9QA3KdQ9qOoBoBsJPTFihnsbwBqMpHjA4SZQIv6FEUKz/zej8VHhUcFtyml1sDMcnhiV3mbGkM60BqKBGb8OVeAfxAw+DTnzkwdwKgdDhh+g3i8jMvc4SlYncjE9Ez+te+zL3PpvB3nN2Mea7B1sHtoQJ4y4WqFo+H75UWHOx7rHOxwZcmKKTc7SJHbqQ23pnIetBrldA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
